### ISSUE TITLE
sys_test_v3 does not compile, it looks like last year's code

### ISSUE THREAD

**Issue by pranavmathur** [Thunderbots-5604/2014-Code#6]
Wasn't there a version that worked? We should test it on Friday (1/9) and put that in master.

@ZachOhara 
@danielgrimshaw 
@zachw000

**Comment by ZachOhara** [comment]
I'm assigning @danielgrimshaw to fix this, since he was the one that replaced the file with last year's in the first place. Once you get that to work (or at least compile), move sys_test_v2 into teleop/old.

Daniel, if you did not do this, look in the file's history and reassign the issue to whoever did change that.

**Comment by ZachOhara** [comment]
Closing: no longer relevant

But @danielgrimshaw, please do this eventually.
